name: Hello World 
on: [push]
jobs: 
  Hello-World: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello World"
      - name: Checkout branch 
        uses: actions/checkout@v3
      - name: List Files 
        run: ls ${{ github.workspace }}
