name: Pull Request 
on: [pull_request]
jobs: 
  PullRequest: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Check"
      - name: Checkout branch 
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with: 
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_POSTGRES_URL: ${{secrets.POSTGRES_URL}}
      - name: RUN TESTS
        run: docker-compose -f docker-compose-test.yml run node-rating npm run test